In [1]:
import requests

url = "https://air-quality.p.rapidapi.com/history/airquality"

querystring = {"lon":"77.7523","lat":"20.932"}

headers = {
	"x-rapidapi-key": "6382b2d0dbmsh60bb1f6c23ea870p155ce0jsnc26410de4c73",
	"x-rapidapi-host": "air-quality.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'city_name': 'AmrƒÅvati', 'country_code': 'IN', 'data': [{'aqi': 58, 'co': 68.7, 'datetime': '2025-03-04:10', 'no2': 1.7, 'o3': 126.3, 'pm10': 39.7, 'pm25': 15.67, 'so2': 18, 'timestamp_local': '2025-03-04T15:30:00', 'timestamp_utc': '2025-03-04T10:00:00', 'ts': 1741082400}, {'aqi': 62, 'co': 68.9, 'datetime': '2025-03-04:09', 'no2': 1, 'o3': 130, 'pm10': 38, 'pm25': 15, 'so2': 18, 'timestamp_local': '2025-03-04T14:30:00', 'timestamp_utc': '2025-03-04T09:00:00', 'ts': 1741078800}, {'aqi': 161, 'co': 572.5, 'datetime': '2025-03-04:08', 'no2': 8, 'o3': 86.6, 'pm10': 85, 'pm25': 63.5, 'so2': 34, 'timestamp_local': '2025-03-04T13:30:00', 'timestamp_utc': '2025-03-04T08:00:00', 'ts': 1741075200}, {'aqi': 139, 'co': 404.6, 'datetime': '2025-03-04:07', 'no2': 7.7, 'o3': 95.4, 'pm10': 72.7, 'pm25': 50, 'so2': 25, 'timestamp_local': '2025-03-04T12:30:00', 'timestamp_utc': '2025-03-04T07:00:00', 'ts': 1741071600}, {'aqi': 166, 'co': 572.5, 'datetime': '2025-03-04:06', 'no2': 11, 'o3': 78.1, 'pm10': 90, 'pm25': 67.5, 'so2': 28.5, 'timestamp_local': '2025-03-04T11:30:00', 'timestamp_utc': '2025-03-04T06:00:00', 'ts': 1741068000}, {'aqi': 152, 'co': 447.2, 'datetime': '2025-03-04:05', 'no2': 11, 'o3': 72.4, 'pm10': 76.3, 'pm25': 57, 'so2': 25.3, 'timestamp_local': '2025-03-04T10:30:00', 'timestamp_utc': '2025-03-04T05:00:00', 'ts': 1741064400}, {'aqi': 181, 'co': 572.5, 'datetime': '2025-03-04:04', 'no2': 17.5, 'o3': 68.1, 'pm10': 105, 'pm25': 78.5, 'so2': 26.5, 'timestamp_local': '2025-03-04T09:30:00', 'timestamp_utc': '2025-03-04T04:00:00', 'ts': 1741060800}, {'aqi': 102, 'co': 196.7, 'datetime': '2025-03-04:03', 'no2': 11, 'o3': 61, 'pm10': 49, 'pm25': 36, 'so2': 19, 'timestamp_local': '2025-03-04T08:30:00', 'timestamp_utc': '2025-03-04T03:00:00', 'ts': 1741057200}, {'aqi': 161, 'co': 0, 'datetime': '2025-03-04:02', 'no2': 43, 'o3': 9.7, 'pm10': 85, 'pm25': 64, 'so2': 11, 'timestamp_local': '2025-03-04T07:30:00', 'timestamp_utc': '2025-03-04T02:00:00', 'ts': 1741053600}, {'aqi': 141, 'co': 447.2, 'datetime': '2025-03-04:01', 'no2': 16.3, 'o3': 43, 'pm10': 68, 'pm25': 50.67, 'so2': 23.3, 'timestamp_local': '2025-03-04T06:30:00', 'timestamp_utc': '2025-03-04T01:00:00', 'ts': 1741050000}, {'aqi': 153, 'co': 572.5, 'datetime': '2025-03-04:00', 'no2': 19, 'o3': 34, 'pm10': 77.5, 'pm25': 58, 'so2': 25.5, 'timestamp_local': '2025-03-04T05:30:00', 'timestamp_utc': '2025-03-04T00:00:00', 'ts': 1741046400}, {'aqi': 140, 'co': 428.9, 'datetime': '2025-03-03:23', 'no2': 16, 'o3': 37.7, 'pm10': 68, 'pm25': 50.33, 'so2': 21.7, 'timestamp_local': '2025-03-04T04:30:00', 'timestamp_utc': '2025-03-03T23:00:00', 'ts': 1741042800}, {'aqi': 155, 'co': 572.5, 'datetime': '2025-03-03:22', 'no2': 13, 'o3': 45.3, 'pm10': 79, 'pm25': 59.5, 'so2': 26.5, 'timestamp_local': '2025-03-04T03:30:00', 'timestamp_utc': '2025-03-03T22:00:00', 'ts': 1741039200}, {'aqi': 100, 'co': 141.8, 'datetime': '2025-03-03:21', 'no2': 10, 'o3': 45, 'pm10': 49, 'pm25': 35, 'so2': 14, 'timestamp_local': '2025-03-04T02:30:00', 'timestamp_utc': '2025-03-03T21:00:00', 'ts': 1741035600}, {'aqi': 165, 'co': 572.5, 'datetime': '2025-03-03:20', 'no2': 14, 'o3': 44.4, 'pm10': 89, 'pm25': 66.5, 'so2': 26, 'timestamp_local': '2025-03-04T01:30:00', 'timestamp_utc': '2025-03-03T20:00:00', 'ts': 1741032000}, {'aqi': 164, 'co': 428.9, 'datetime': '2025-03-03:19', 'no2': 15.7, 'o3': 45.9, 'pm10': 88.7, 'pm25': 66, 'so2': 23, 'timestamp_local': '2025-03-04T00:30:00', 'timestamp_utc': '2025-03-03T19:00:00', 'ts': 1741028400}, {'aqi': 185, 'co': 572.5, 'datetime': '2025-03-03:18', 'no2': 18.5, 'o3': 46.4, 'pm10': 108.5, 'pm25': 81.5, 'so2': 27.5, 'timestamp_local': '2025-03-03T23:30:00', 'timestamp_utc': '2025-03-03T18:00:00', 'ts': 1741024800}, {'aqi': 161, 'co': 430.7, 'datetime': '2025-03-03:17', 'no2': 18.3, 'o3': 57.9, 'pm10': 88, 'pm25': 64, 'so2': 28.7, 'timestamp_local': '2025-03-03T22:30:00', 'timestamp_utc': '2025-03-03T17:00:00', 'ts': 1741021200}, {'aqi': 180, 'co': 572.5, 'datetime': '2025-03-03:16', 'no2': 44, 'o3': 23.9, 'pm10': 104, 'pm25': 78, 'so2': 28, 'timestamp_local': '2025-03-03T21:30:00', 'timestamp_utc': '2025-03-03T16:00:00', 'ts': 1741017600}, {'aqi': 87, 'co': 147.1, 'datetime': '2025-03-03:15', 'no2': 18, 'o3': 81, 'pm10': 47, 'pm25': 29, 'so2': 31, 'timestamp_local': '2025-03-03T20:30:00', 'timestamp_utc': '2025-03-03T15:00:00', 'ts': 1741014000}, {'aqi': 192, 'co': 1145, 'datetime': '2025-03-03:14', 'no2': 39, 'o3': 35.4, 'pm10': 116, 'pm25': 87, 'so2': 27, 'timestamp_local': '2025-03-03T19:30:00', 'timestamp_utc': '2025-03-03T14:00:00', 'ts': 1741010400}, {'aqi': 130, 'co': 430.7, 'datetime': '2025-03-03:13', 'no2': 22.7, 'o3': 58, 'pm10': 64.3, 'pm25': 46.33, 'so2': 25, 'timestamp_local': '2025-03-03T18:30:00', 'timestamp_utc': '2025-03-03T13:00:00', 'ts': 1741006800}, {'aqi': 153, 'co': 572.5, 'datetime': '2025-03-03:12', 'no2': 25, 'o3': 46.6, 'pm10': 73, 'pm25': 55, 'so2': 22, 'timestamp_local': '2025-03-03T17:30:00', 'timestamp_utc': '2025-03-03T12:00:00', 'ts': 1741003200}, {'aqi': 152, 'co': 572.5, 'datetime': '2025-03-03:11', 'no2': 20.3, 'o3': 55.2, 'pm10': 75.8, 'pm25': 57, 'so2': 22.3, 'timestamp_local': '2025-03-03T16:30:00', 'timestamp_utc': '2025-03-03T11:00:00', 'ts': 1740999600}, {'aqi': 155, 'co': 572.5, 'datetime': '2025-03-03:10', 'no2': 15.7, 'o3': 63.8, 'pm10': 78.7, 'pm25': 59, 'so2': 22.7, 'timestamp_local': '2025-03-03T15:30:00', 'timestamp_utc': '2025-03-03T10:00:00', 'ts': 1740996000}, {'aqi': 157, 'co': 572.5, 'datetime': '2025-03-03:09', 'no2': 11, 'o3': 72.5, 'pm10': 81.5, 'pm25': 61, 'so2': 23, 'timestamp_local': '2025-03-03T14:30:00', 'timestamp_utc': '2025-03-03T09:00:00', 'ts': 1740992400}, {'aqi': 172, 'co': 572.5, 'datetime': '2025-03-03:08', 'no2': 9.5, 'o3': 73, 'pm10': 96, 'pm25': 72, 'so2': 21, 'timestamp_local': '2025-03-03T13:30:00', 'timestamp_utc': '2025-03-03T08:00:00', 'ts': 1740988800}, {'aqi': 175, 'co': 954.2, 'datetime': '2025-03-03:07', 'no2': 8.3, 'o3': 70.4, 'pm10': 99.2, 'pm25': 74.33, 'so2': 37, 'timestamp_local': '2025-03-03T12:30:00', 'timestamp_utc': '2025-03-03T07:00:00', 'ts': 1740985200}, {'aqi': 184, 'co': 1145, 'datetime': '2025-03-03:06', 'no2': 7, 'o3': 69.3, 'pm10': 108, 'pm25': 81, 'so2': 44, 'timestamp_local': '2025-03-03T11:30:00', 'timestamp_utc': '2025-03-03T06:00:00', 'ts': 1740981600}, {'aqi': 193, 'co': 0, 'datetime': '2025-03-03:05', 'no2': 12, 'o3': 62.8, 'pm10': 117, 'pm25': 88, 'so2': 9, 'timestamp_local': '2025-03-03T10:30:00', 'timestamp_utc': '2025-03-03T05:00:00', 'ts': 1740978000}, {'aqi': 189, 'co': 572.5, 'datetime': '2025-03-03:04', 'no2': 17, 'o3': 66.1, 'pm10': 112.5, 'pm25': 84.5, 'so2': 30, 'timestamp_local': '2025-03-03T09:30:00', 'timestamp_utc': '2025-03-03T04:00:00', 'ts': 1740974400}, {'aqi': 80, 'co': 183.3, 'datetime': '2025-03-03:03', 'no2': 9, 'o3': 56, 'pm10': 40, 'pm25': 26, 'so2': 16, 'timestamp_local': '2025-03-03T08:30:00', 'timestamp_utc': '2025-03-03T03:00:00', 'ts': 1740970800}, {'aqi': 165, 'co': 572.5, 'datetime': '2025-03-03:02', 'no2': 28.5, 'o3': 31.9, 'pm10': 89, 'pm25': 67, 'so2': 30, 'timestamp_local': '2025-03-03T07:30:00', 'timestamp_utc': '2025-03-03T02:00:00', 'ts': 1740967200}, {'aqi': 139, 'co': 442.8, 'datetime': '2025-03-03:01', 'no2': 12.7, 'o3': 40.8, 'pm10': 68.3, 'pm25': 50, 'so2': 23.3, 'timestamp_local': '2025-03-03T06:30:00', 'timestamp_utc': '2025-03-03T01:00:00', 'ts': 1740963600}, {'aqi': 159, 'co': 572.5, 'datetime': '2025-03-03:00', 'no2': 14.5, 'o3': 33.2, 'pm10': 82.5, 'pm25': 62, 'so2': 27, 'timestamp_local': '2025-03-03T05:30:00', 'timestamp_utc': '2025-03-03T00:00:00', 'ts': 1740960000}, {'aqi': 141, 'co': 425, 'datetime': '2025-03-02:23', 'no2': 12.7, 'o3': 39.1, 'pm10': 71.3, 'pm25': 50.67, 'so2': 25, 'timestamp_local': '2025-03-03T04:30:00', 'timestamp_utc': '2025-03-02T23:00:00', 'ts': 1740956400}, {'aqi': 169, 'co': 572.5, 'datetime': '2025-03-02:22', 'no2': 22, 'o3': 26.6, 'pm10': 92, 'pm25': 69.5, 'so2': 31, 'timestamp_local': '2025-03-03T03:30:00', 'timestamp_utc': '2025-03-02T22:00:00', 'ts': 1740952800}, {'aqi': 85, 'co': 130.1, 'datetime': '2025-03-02:21', 'no2': 9, 'o3': 51, 'pm10': 49, 'pm25': 28, 'so2': 21, 'timestamp_local': '2025-03-03T02:30:00', 'timestamp_utc': '2025-03-02T21:00:00', 'ts': 1740949200}, {'aqi': 178, 'co': 572.5, 'datetime': '2025-03-02:20', 'no2': 27.5, 'o3': 29.6, 'pm10': 101.5, 'pm25': 76.5, 'so2': 29, 'timestamp_local': '2025-03-03T01:30:00', 'timestamp_utc': '2025-03-02T20:00:00', 'ts': 1740945600}, {'aqi': 171, 'co': 425, 'datetime': '2025-03-02:19', 'no2': 22.3, 'o3': 44.9, 'pm10': 98.7, 'pm25': 71, 'so2': 25, 'timestamp_local': '2025-03-03T00:30:00', 'timestamp_utc': '2025-03-02T19:00:00', 'ts': 1740942000}, {'aqi': 199, 'co': 572.5, 'datetime': '2025-03-02:18', 'no2': 29, 'o3': 41.8, 'pm10': 123.5, 'pm25': 92.5, 'so2': 27, 'timestamp_local': '2025-03-02T23:30:00', 'timestamp_utc': '2025-03-02T18:00:00', 'ts': 1740938400}, {'aqi': 173, 'co': 419.8, 'datetime': '2025-03-02:17', 'no2': 22.3, 'o3': 60.2, 'pm10': 96.7, 'pm25': 72.67, 'so2': 29.7, 'timestamp_local': '2025-03-02T22:30:00', 'timestamp_utc': '2025-03-02T17:00:00', 'ts': 1740934800}, {'aqi': 191, 'co': 1717.5, 'datetime': '2025-03-02:16', 'no2': 68, 'o3': 13.2, 'pm10': 114.5, 'pm25': 86, 'so2': 30, 'timestamp_local': '2025-03-02T21:30:00', 'timestamp_utc': '2025-03-02T16:00:00', 'ts': 1740931200}, {'aqi': 95, 'co': 114.4, 'datetime': '2025-03-02:15', 'no2': 9, 'o3': 97, 'pm10': 43, 'pm25': 33, 'so2': 35, 'timestamp_local': '2025-03-02T20:30:00', 'timestamp_utc': '2025-03-02T15:00:00', 'ts': 1740927600}, {'aqi': 173, 'co': 572.5, 'datetime': '2025-03-02:14', 'no2': 30, 'o3': 54, 'pm10': 96.5, 'pm25': 72.5, 'so2': 30.5, 'timestamp_local': '2025-03-02T19:30:00', 'timestamp_utc': '2025-03-02T14:00:00', 'ts': 1740924000}, {'aqi': 92, 'co': 92.6, 'datetime': '2025-03-02:13', 'no2': 5, 'o3': 129, 'pm10': 44.3, 'pm25': 31.67, 'so2': 32.3, 'timestamp_local': '2025-03-02T18:30:00', 'timestamp_utc': '2025-03-02T13:00:00', 'ts': 1740920400}, {'aqi': 91, 'co': 81.7, 'datetime': '2025-03-02:12', 'no2': 3, 'o3': 145, 'pm10': 45, 'pm25': 31, 'so2': 31, 'timestamp_local': '2025-03-02T17:30:00', 'timestamp_utc': '2025-03-02T12:00:00', 'ts': 1740916800}, {'aqi': 171, 'co': 1145, 'datetime': '2025-03-02:11', 'no2': 7, 'o3': 93.2, 'pm10': 94, 'pm25': 71, 'so2': 55, 'timestamp_local': '2025-03-02T16:30:00', 'timestamp_utc': '2025-03-02T11:00:00', 'ts': 1740913200}, {'aqi': 169, 'co': 572.5, 'datetime': '2025-03-02:10', 'no2': 7.5, 'o3': 102, 'pm10': 93.5, 'pm25': 70, 'so2': 39.5, 'timestamp_local': '2025-03-02T15:30:00', 'timestamp_utc': '2025-03-02T10:00:00', 'ts': 1740909600}, {'aqi': 101, 'co': 90.5, 'datetime': '2025-03-02:09', 'no2': 2, 'o3': 162, 'pm10': 37, 'pm25': 27, 'so2': 37, 'timestamp_local': '2025-03-02T14:30:00', 'timestamp_utc': '2025-03-02T09:00:00', 'ts': 1740906000}, {'aqi': 169, 'co': 572.5, 'datetime': '2025-03-02:08', 'no2': 8.5, 'o3': 97.6, 'pm10': 93, 'pm25': 70, 'so2': 41, 'timestamp_local': '2025-03-02T13:30:00', 'timestamp_utc': '2025-03-02T08:00:00', 'ts': 1740902400}, {'aqi': 166, 'co': 411.8, 'datetime': '2025-03-02:07', 'no2': 8.3, 'o3': 99.4, 'pm10': 90, 'pm25': 67.33, 'so2': 33.7, 'timestamp_local': '2025-03-02T12:30:00', 'timestamp_utc': '2025-03-02T07:00:00', 'ts': 1740898800}, {'aqi': 193, 'co': 572.5, 'datetime': '2025-03-02:06', 'no2': 11.5, 'o3': 68.1, 'pm10': 116.5, 'pm25': 87.5, 'so2': 32, 'timestamp_local': '2025-03-02T11:30:00', 'timestamp_utc': '2025-03-02T06:00:00', 'ts': 1740895200}, {'aqi': 171, 'co': 471.2, 'datetime': '2025-03-02:05', 'no2': 12, 'o3': 69.8, 'pm10': 92, 'pm25': 71.33, 'so2': 32.7, 'timestamp_local': '2025-03-02T10:30:00', 'timestamp_utc': '2025-03-02T05:00:00', 'ts': 1740891600}, {'aqi': 195, 'co': 0, 'datetime': '2025-03-02:04', 'no2': 24, 'o3': 69.5, 'pm10': 119, 'pm25': 89, 'so2': 21, 'timestamp_local': '2025-03-02T09:30:00', 'timestamp_utc': '2025-03-02T04:00:00', 'ts': 1740888000}, {'aqi': 110, 'co': 268.5, 'datetime': '2025-03-02:03', 'no2': 13, 'o3': 73, 'pm10': 43, 'pm25': 39, 'so2': 34, 'timestamp_local': '2025-03-02T08:30:00', 'timestamp_utc': '2025-03-02T03:00:00', 'ts': 1740884400}, {'aqi': 190, 'co': 1145, 'datetime': '2025-03-02:02', 'no2': 41.5, 'o3': 21.7, 'pm10': 114, 'pm25': 85.5, 'so2': 28, 'timestamp_local': '2025-03-02T07:30:00', 'timestamp_utc': '2025-03-02T02:00:00', 'ts': 1740880800}, {'aqi': 155, 'co': 471.2, 'datetime': '2025-03-02:01', 'no2': 27, 'o3': 38.5, 'pm10': 76, 'pm25': 59.33, 'so2': 30.7, 'timestamp_local': '2025-03-02T06:30:00', 'timestamp_utc': '2025-03-02T01:00:00', 'ts': 1740877200}, {'aqi': 169, 'co': 572.5, 'datetime': '2025-03-02:00', 'no2': 34, 'o3': 21.3, 'pm10': 92.5, 'pm25': 69.5, 'so2': 29, 'timestamp_local': '2025-03-02T05:30:00', 'timestamp_utc': '2025-03-02T00:00:00', 'ts': 1740873600}, {'aqi': 157, 'co': 467.1, 'datetime': '2025-03-01:23', 'no2': 29, 'o3': 32.2, 'pm10': 77.3, 'pm25': 61, 'so2': 32.3, 'timestamp_local': '2025-03-02T04:30:00', 'timestamp_utc': '2025-03-01T23:00:00', 'ts': 1740870000}, {'aqi': 168, 'co': 572.5, 'datetime': '2025-03-01:22', 'no2': 16, 'o3': 51.1, 'pm10': 92, 'pm25': 69, 'so2': 31, 'timestamp_local': '2025-03-02T03:30:00', 'timestamp_utc': '2025-03-01T22:00:00', 'ts': 1740866400}, {'aqi': 123, 'co': 256.2, 'datetime': '2025-03-01:21', 'no2': 19, 'o3': 54, 'pm10': 47, 'pm25': 44, 'so2': 39, 'timestamp_local': '2025-03-02T02:30:00', 'timestamp_utc': '2025-03-01T21:00:00', 'ts': 1740862800}, {'aqi': 210, 'co': 572.5, 'datetime': '2025-03-01:20', 'no2': 15.5, 'o3': 68.4, 'pm10': 134, 'pm25': 100.5, 'so2': 39, 'timestamp_local': '2025-03-02T01:30:00', 'timestamp_utc': '2025-03-01T20:00:00', 'ts': 1740859200}, {'aqi': 184, 'co': 85.4, 'datetime': '2025-03-01:19', 'no2': 47, 'o3': 27.4, 'pm10': 104.3, 'pm25': 81.33, 'so2': 21.7, 'timestamp_local': '2025-03-02T00:30:00', 'timestamp_utc': '2025-03-01T19:00:00', 'ts': 1740855600}, {'aqi': 209, 'co': 0, 'datetime': '2025-03-01:18', 'no2': 61, 'o3': 14.1, 'pm10': 133, 'pm25': 100, 'so2': 13, 'timestamp_local': '2025-03-01T23:30:00', 'timestamp_utc': '2025-03-01T18:00:00', 'ts': 1740852000}, {'aqi': 185, 'co': 61.1, 'datetime': '2025-03-01:17', 'no2': 46.7, 'o3': 41.8, 'pm10': 105.7, 'pm25': 82, 'so2': 19, 'timestamp_local': '2025-03-01T22:30:00', 'timestamp_utc': '2025-03-01T17:00:00', 'ts': 1740848400}, {'aqi': 228, 'co': 0, 'datetime': '2025-03-01:16', 'no2': 55, 'o3': 27, 'pm10': 152, 'pm25': 114, 'so2': 14, 'timestamp_local': '2025-03-01T21:30:00', 'timestamp_utc': '2025-03-01T16:00:00', 'ts': 1740844800}, {'aqi': 129, 'co': 183.3, 'datetime': '2025-03-01:15', 'no2': 18, 'o3': 97, 'pm10': 51, 'pm25': 46, 'so2': 31, 'timestamp_local': '2025-03-01T20:30:00', 'timestamp_utc': '2025-03-01T15:00:00', 'ts': 1740841200}, {'aqi': 199, 'co': 0, 'datetime': '2025-03-01:14', 'no2': 74, 'o3': 14.3, 'pm10': 122, 'pm25': 92, 'so2': 11, 'timestamp_local': '2025-03-01T19:30:00', 'timestamp_utc': '2025-03-01T14:00:00', 'ts': 1740837600}, {'aqi': 154, 'co': 442.8, 'datetime': '2025-03-01:13', 'no2': 21.7, 'o3': 81, 'pm10': 74.3, 'pm25': 58.33, 'so2': 29.7, 'timestamp_local': '2025-03-01T18:30:00', 'timestamp_utc': '2025-03-01T13:00:00', 'ts': 1740834000}, {'aqi': 162, 'co': 572.5, 'datetime': '2025-03-01:12', 'no2': 23.5, 'o3': 73, 'pm10': 86, 'pm25': 64.5, 'so2': 29, 'timestamp_local': '2025-03-01T17:30:00', 'timestamp_utc': '2025-03-01T12:00:00', 'ts': 1740830400}, {'aqi': 149, 'co': 412.2, 'datetime': '2025-03-01:11', 'no2': 16, 'o3': 100.3, 'pm10': 69.7, 'pm25': 53.67, 'so2': 28.3, 'timestamp_local': '2025-03-01T16:30:00', 'timestamp_utc': '2025-03-01T11:00:00', 'ts': 1740826800}], 'lat': 20.932, 'lon': 77.7523, 'state_code': '16', 'timezone': 'Asia/Kolkata'}

In [2]:
import pandas as pd
import pandas as pd
data = response.json()['data']
data = pd.DataFrame(data)
data

,aqi,co,datetime,no2,o3,pm10,pm25,so2,timestamp_local,timestamp_utc,ts
0,58,68.7,2025-03-04:10,1.7,126.3,39.7,15.67,18.0,2025-03-04T15:30:00,2025-03-04T10:00:00,1741082400
1,62,68.9,2025-03-04:09,1.0,130.0,38.0,15.00,18.0,2025-03-04T14:30:00,2025-03-04T09:00:00,1741078800
2,161,572.5,2025-03-04:08,8.0,86.6,85.0,63.50,34.0,2025-03-04T13:30:00,2025-03-04T08:00:00,1741075200
3,139,404.6,2025-03-04:07,7.7,95.4,72.7,50.00,25.0,2025-03-04T12:30:00,2025-03-04T07:00:00,1741071600
4,166,572.5,2025-03-04:06,11.0,78.1,90.0,67.50,28.5,2025-03-04T11:30:00,2025-03-04T06:00:00,1741068000
...,...,...,...,...,...,...,...,...,...,...,...
67,129,183.3,2025-03-01:15,18.0,97.0,51.0,46.00,31.0,2025-03-01T20:30:00,2025-03-01T15:00:00,1740841200
68,199,0.0,2025-03-01:14,74.0,14.3,122.0,92.00,11.0,2025-03-01T19:30:00,2025-03-01T14:00:00,1740837600
69,154,442.8,2025-03-01:13,21.7,81.0,74.3,58.33,29.7,2025-03-01T18:30:00,2025-03-01T13:00:00,1740834000
70,162,572.5,2025-03-01:12,23.5,73.0,86.0,64.50,29.0,2025-03-01T17:30:00,2025-03-01T12:00:00,1740830400
71,149,412.2,2025-03-01:11,16.0,100.3,69.7,53.67,28.3,2025-03-01T16:30:00,2025-03-01T11:00:00,1740826800

In [3]:
data['city_name'] = 'Amravati'
data

,aqi,co,datetime,no2,o3,pm10,pm25,so2,timestamp_local,timestamp_utc,ts,city_name
0,58,68.7,2025-03-04:10,1.7,126.3,39.7,15.67,18.0,2025-03-04T15:30:00,2025-03-04T10:00:00,1741082400,Amravati
1,62,68.9,2025-03-04:09,1.0,130.0,38.0,15.00,18.0,2025-03-04T14:30:00,2025-03-04T09:00:00,1741078800,Amravati
2,161,572.5,2025-03-04:08,8.0,86.6,85.0,63.50,34.0,2025-03-04T13:30:00,2025-03-04T08:00:00,1741075200,Amravati
3,139,404.6,2025-03-04:07,7.7,95.4,72.7,50.00,25.0,2025-03-04T12:30:00,2025-03-04T07:00:00,1741071600,Amravati
4,166,572.5,2025-03-04:06,11.0,78.1,90.0,67.50,28.5,2025-03-04T11:30:00,2025-03-04T06:00:00,1741068000,Amravati
...,...,...,...,...,...,...,...,...,...,...,...,...
67,129,183.3,2025-03-01:15,18.0,97.0,51.0,46.00,31.0,2025-03-01T20:30:00,2025-03-01T15:00:00,1740841200,Amravati
68,199,0.0,2025-03-01:14,74.0,14.3,122.0,92.00,11.0,2025-03-01T19:30:00,2025-03-01T14:00:00,1740837600,Amravati
69,154,442.8,2025-03-01:13,21.7,81.0,74.3,58.33,29.7,2025-03-01T18:30:00,2025-03-01T13:00:00,1740834000,Amravati
70,162,572.5,2025-03-01:12,23.5,73.0,86.0,64.50,29.0,2025-03-01T17:30:00,2025-03-01T12:00:00,1740830400,Amravati
71,149,412.2,2025-03-01:11,16.0,100.3,69.7,53.67,28.3,2025-03-01T16:30:00,2025-03-01T11:00:00,1740826800,Amravati

In [4]:
data.to_csv('datasets/Amravati.csv')