In [1]:
import requests

url = "https://air-quality.p.rapidapi.com/history/airquality"

querystring = {"lon":"83.0024","lat":"17.6896"}

headers = {
	"x-rapidapi-key": "6382b2d0dbmsh60bb1f6c23ea870p155ce0jsnc26410de4c73",
	"x-rapidapi-host": "air-quality.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'city_name': 'AnakƒÅpalle', 'country_code': 'IN', 'data': [{'aqi': 52, 'co': 353, 'datetime': '2025-03-04:09', 'no2': 132, 'o3': 5.2, 'pm10': 58, 'pm25': 13, 'so2': 23, 'timestamp_local': '2025-03-04T14:30:00', 'timestamp_utc': '2025-03-04T09:00:00', 'ts': 1741078800}, {'aqi': 100, 'co': 252, 'datetime': '2025-03-04:08', 'no2': 105, 'o3': 8.6, 'pm10': 73, 'pm25': 35, 'so2': 22.5, 'timestamp_local': '2025-03-04T13:30:00', 'timestamp_utc': '2025-03-04T08:00:00', 'ts': 1741075200}, {'aqi': 150, 'co': 675, 'datetime': '2025-03-04:07', 'no2': 139, 'o3': 6.1, 'pm10': 128, 'pm25': 54, 'so2': 13, 'timestamp_local': '2025-03-04T12:30:00', 'timestamp_utc': '2025-03-04T07:00:00', 'ts': 1741071600}, {'aqi': 171, 'co': 338, 'datetime': '2025-03-04:06', 'no2': 113.5, 'o3': 9.9, 'pm10': 125, 'pm25': 71.5, 'so2': 11.5, 'timestamp_local': '2025-03-04T11:30:00', 'timestamp_utc': '2025-03-04T06:00:00', 'ts': 1741068000}, {'aqi': 171, 'co': 474, 'datetime': '2025-03-04:05', 'no2': 133, 'o3': 7.8, 'pm10': 156, 'pm25': 71.33, 'so2': 13, 'timestamp_local': '2025-03-04T10:30:00', 'timestamp_utc': '2025-03-04T05:00:00', 'ts': 1741064400}, {'aqi': 163, 'co': 288, 'datetime': '2025-03-04:04', 'no2': 119, 'o3': 6.8, 'pm10': 121.5, 'pm25': 65.5, 'so2': 12, 'timestamp_local': '2025-03-04T09:30:00', 'timestamp_utc': '2025-03-04T04:00:00', 'ts': 1741060800}, {'aqi': 171, 'co': 746, 'datetime': '2025-03-04:03', 'no2': 172, 'o3': 3.6, 'pm10': 218, 'pm25': 71, 'so2': 16, 'timestamp_local': '2025-03-04T08:30:00', 'timestamp_utc': '2025-03-04T03:00:00', 'ts': 1741057200}, {'aqi': 231, 'co': 479.5, 'datetime': '2025-03-04:02', 'no2': 100.5, 'o3': 6.9, 'pm10': 195.5, 'pm25': 116.5, 'so2': 25.5, 'timestamp_local': '2025-03-04T07:30:00', 'timestamp_utc': '2025-03-04T02:00:00', 'ts': 1741053600}, {'aqi': 104, 'co': 544, 'datetime': '2025-03-04:01', 'no2': 117, 'o3': 4.2, 'pm10': 82, 'pm25': 37, 'so2': 23, 'timestamp_local': '2025-03-04T06:30:00', 'timestamp_utc': '2025-03-04T01:00:00', 'ts': 1741050000}, {'aqi': 176, 'co': 1145, 'datetime': '2025-03-04:00', 'no2': 66, 'o3': 10.6, 'pm10': 100, 'pm25': 75, 'so2': 20, 'timestamp_local': '2025-03-04T05:30:00', 'timestamp_utc': '2025-03-04T00:00:00', 'ts': 1741046400}, {'aqi': 78, 'co': 262, 'datetime': '2025-03-03:23', 'no2': 96, 'o3': 4.2, 'pm10': 62, 'pm25': 25, 'so2': 21, 'timestamp_local': '2025-03-04T04:30:00', 'timestamp_utc': '2025-03-03T23:00:00', 'ts': 1741042800}, {'aqi': 102, 'co': 96, 'datetime': '2025-03-03:22', 'no2': 63.5, 'o3': 7.3, 'pm10': 64, 'pm25': 36, 'so2': 8, 'timestamp_local': '2025-03-04T03:30:00', 'timestamp_utc': '2025-03-03T22:00:00', 'ts': 1741039200}, {'aqi': 98, 'co': 202, 'datetime': '2025-03-03:21', 'no2': 105, 'o3': 4.1, 'pm10': 92, 'pm25': 34, 'so2': 12, 'timestamp_local': '2025-03-04T02:30:00', 'timestamp_utc': '2025-03-03T21:00:00', 'ts': 1741035600}, {'aqi': 153, 'co': 101, 'datetime': '2025-03-03:20', 'no2': 87, 'o3': 6.9, 'pm10': 90, 'pm25': 55, 'so2': 13.5, 'timestamp_local': '2025-03-04T01:30:00', 'timestamp_utc': '2025-03-03T20:00:00', 'ts': 1741032000}, {'aqi': 63, 'co': 333, 'datetime': '2025-03-03:19', 'no2': 122, 'o3': 4.1, 'pm10': 56, 'pm25': 18, 'so2': 22, 'timestamp_local': '2025-03-04T00:30:00', 'timestamp_utc': '2025-03-03T19:00:00', 'ts': 1741028400}, {'aqi': 90, 'co': 216.5, 'datetime': '2025-03-03:18', 'no2': 91, 'o3': 7, 'pm10': 58, 'pm25': 30.5, 'so2': 23.5, 'timestamp_local': '2025-03-03T23:30:00', 'timestamp_utc': '2025-03-03T18:00:00', 'ts': 1741024800}, {'aqi': 97, 'co': 954, 'datetime': '2025-03-03:17', 'no2': 108.7, 'o3': 6.1, 'pm10': 92, 'pm25': 33.67, 'so2': 18.7, 'timestamp_local': '2025-03-03T22:30:00', 'timestamp_utc': '2025-03-03T17:00:00', 'ts': 1741021200}, {'aqi': 93, 'co': 873, 'datetime': '2025-03-03:16', 'no2': 101, 'o3': 6.9, 'pm10': 64.5, 'pm25': 32, 'so2': 23, 'timestamp_local': '2025-03-03T21:30:00', 'timestamp_utc': '2025-03-03T16:00:00', 'ts': 1741017600}, {'aqi': 112, 'co': 2429, 'datetime': '2025-03-03:15', 'no2': 144, 'o3': 4.4, 'pm10': 160, 'pm25': 40, 'so2': 9, 'timestamp_local': '2025-03-03T20:30:00', 'timestamp_utc': '2025-03-03T15:00:00', 'ts': 1741014000}, {'aqi': 134, 'co': 677, 'datetime': '2025-03-03:14', 'no2': 107, 'o3': 7.1, 'pm10': 129.5, 'pm25': 48, 'so2': 8.5, 'timestamp_local': '2025-03-03T19:30:00', 'timestamp_utc': '2025-03-03T14:00:00', 'ts': 1741010400}, {'aqi': 78, 'co': 635, 'datetime': '2025-03-03:13', 'no2': 139, 'o3': 4.2, 'pm10': 88, 'pm25': 25, 'so2': 10, 'timestamp_local': '2025-03-03T18:30:00', 'timestamp_utc': '2025-03-03T13:00:00', 'ts': 1741006800}, {'aqi': 199, 'co': 1145, 'datetime': '2025-03-03:12', 'no2': 75, 'o3': 9.4, 'pm10': 122, 'pm25': 92, 'so2': 10, 'timestamp_local': '2025-03-03T17:30:00', 'timestamp_utc': '2025-03-03T12:00:00', 'ts': 1741003200}, {'aqi': 61, 'co': 60, 'datetime': '2025-03-03:11', 'no2': 146, 'o3': 4.2, 'pm10': 54, 'pm25': 17, 'so2': 8, 'timestamp_local': '2025-03-03T16:30:00', 'timestamp_utc': '2025-03-03T11:00:00', 'ts': 1740999600}, {'aqi': 52, 'co': 60, 'datetime': '2025-03-03:10', 'no2': 164, 'o3': 4.5, 'pm10': 56, 'pm25': 13, 'so2': 7, 'timestamp_local': '2025-03-03T15:30:00', 'timestamp_utc': '2025-03-03T10:00:00', 'ts': 1740996000}, {'aqi': 89, 'co': 60, 'datetime': '2025-03-03:09', 'no2': 140, 'o3': 7.2, 'pm10': 74.5, 'pm25': 30, 'so2': 6.5, 'timestamp_local': '2025-03-03T14:30:00', 'timestamp_utc': '2025-03-03T09:00:00', 'ts': 1740992400}, {'aqi': 125, 'co': 60, 'datetime': '2025-03-03:08', 'no2': 153.5, 'o3': 6.2, 'pm10': 100, 'pm25': 44.5, 'so2': 5, 'timestamp_local': '2025-03-03T13:30:00', 'timestamp_utc': '2025-03-03T08:00:00', 'ts': 1740988800}, {'aqi': 160, 'co': 55.5, 'datetime': '2025-03-03:07', 'no2': 150.5, 'o3': 6.6, 'pm10': 131, 'pm25': 63, 'so2': 15, 'timestamp_local': '2025-03-03T12:30:00', 'timestamp_utc': '2025-03-03T07:00:00', 'ts': 1740985200}, {'aqi': 118, 'co': 514, 'datetime': '2025-03-03:06', 'no2': 212, 'o3': 5, 'pm10': 154, 'pm25': 42, 'so2': 27, 'timestamp_local': '2025-03-03T11:30:00', 'timestamp_utc': '2025-03-03T06:00:00', 'ts': 1740981600}, {'aqi': 228, 'co': 0, 'datetime': '2025-03-03:05', 'no2': 104, 'o3': 9.4, 'pm10': 152, 'pm25': 114, 'so2': 26, 'timestamp_local': '2025-03-03T10:30:00', 'timestamp_utc': '2025-03-03T05:00:00', 'ts': 1740978000}, {'aqi': 195, 'co': 333, 'datetime': '2025-03-03:04', 'no2': 141.5, 'o3': 6.8, 'pm10': 153, 'pm25': 89.5, 'so2': 23, 'timestamp_local': '2025-03-03T09:30:00', 'timestamp_utc': '2025-03-03T04:00:00', 'ts': 1740974400}, {'aqi': 93, 'co': 595, 'datetime': '2025-03-03:03', 'no2': 149, 'o3': 4.3, 'pm10': 92, 'pm25': 32, 'so2': 22, 'timestamp_local': '2025-03-03T08:30:00', 'timestamp_utc': '2025-03-03T03:00:00', 'ts': 1740970800}, {'aqi': 152, 'co': 217, 'datetime': '2025-03-03:02', 'no2': 104, 'o3': 7.2, 'pm10': 92, 'pm25': 54.5, 'so2': 20, 'timestamp_local': '2025-03-03T07:30:00', 'timestamp_utc': '2025-03-03T02:00:00', 'ts': 1740967200}, {'aqi': 110, 'co': 343, 'datetime': '2025-03-03:01', 'no2': 132, 'o3': 4.4, 'pm10': 82, 'pm25': 39, 'so2': 16, 'timestamp_local': '2025-03-03T06:30:00', 'timestamp_utc': '2025-03-03T01:00:00', 'ts': 1740963600}, {'aqi': 155, 'co': 0, 'datetime': '2025-03-03:00', 'no2': 65, 'o3': 9.7, 'pm10': 79, 'pm25': 59, 'so2': 16, 'timestamp_local': '2025-03-03T05:30:00', 'timestamp_utc': '2025-03-03T00:00:00', 'ts': 1740960000}, {'aqi': 118, 'co': 232, 'datetime': '2025-03-02:23', 'no2': 126, 'o3': 4.2, 'pm10': 80, 'pm25': 42, 'so2': 16, 'timestamp_local': '2025-03-03T04:30:00', 'timestamp_utc': '2025-03-02T23:00:00', 'ts': 1740956400}, {'aqi': 123, 'co': 111, 'datetime': '2025-03-02:22', 'no2': 96, 'o3': 7, 'pm10': 76.5, 'pm25': 44, 'so2': 12.5, 'timestamp_local': '2025-03-03T03:30:00', 'timestamp_utc': '2025-03-02T22:00:00', 'ts': 1740952800}, {'aqi': 69, 'co': 212, 'datetime': '2025-03-02:21', 'no2': 135, 'o3': 4, 'pm10': 58, 'pm25': 21, 'so2': 15, 'timestamp_local': '2025-03-03T02:30:00', 'timestamp_utc': '2025-03-02T21:00:00', 'ts': 1740949200}, {'aqi': 98, 'co': 156, 'datetime': '2025-03-02:20', 'no2': 108, 'o3': 6.4, 'pm10': 61.5, 'pm25': 34, 'so2': 14.5, 'timestamp_local': '2025-03-03T01:30:00', 'timestamp_utc': '2025-03-02T20:00:00', 'ts': 1740945600}, {'aqi': 89, 'co': 343, 'datetime': '2025-03-02:19', 'no2': 173, 'o3': 3.9, 'pm10': 72, 'pm25': 30, 'so2': 15, 'timestamp_local': '2025-03-03T00:30:00', 'timestamp_utc': '2025-03-02T19:00:00', 'ts': 1740942000}, {'aqi': 155, 'co': 0, 'datetime': '2025-03-02:18', 'no2': 93, 'o3': 11, 'pm10': 79, 'pm25': 59, 'so2': 15, 'timestamp_local': '2025-03-02T23:30:00', 'timestamp_utc': '2025-03-02T18:00:00', 'ts': 1740938400}, {'aqi': 80, 'co': 403, 'datetime': '2025-03-02:17', 'no2': 180, 'o3': 4.2, 'pm10': 66, 'pm25': 26, 'so2': 16, 'timestamp_local': '2025-03-02T22:30:00', 'timestamp_utc': '2025-03-02T17:00:00', 'ts': 1740934800}, {'aqi': 114, 'co': 247.5, 'datetime': '2025-03-02:16', 'no2': 123.5, 'o3': 7.1, 'pm10': 82.5, 'pm25': 40.5, 'so2': 13.5, 'timestamp_local': '2025-03-02T21:30:00', 'timestamp_utc': '2025-03-02T16:00:00', 'ts': 1740931200}, {'aqi': 123, 'co': 776, 'datetime': '2025-03-02:15', 'no2': 187, 'o3': 4.3, 'pm10': 160, 'pm25': 44, 'so2': 13, 'timestamp_local': '2025-03-02T20:30:00', 'timestamp_utc': '2025-03-02T15:00:00', 'ts': 1740927600}, {'aqi': 168, 'co': 504.5, 'datetime': '2025-03-02:14', 'no2': 168.5, 'o3': 6.9, 'pm10': 149.5, 'pm25': 69, 'so2': 11.5, 'timestamp_local': '2025-03-02T19:30:00', 'timestamp_utc': '2025-03-02T14:00:00', 'ts': 1740924000}, {'aqi': 67, 'co': 796, 'datetime': '2025-03-02:13', 'no2': 198, 'o3': 4.6, 'pm10': 82, 'pm25': 20, 'so2': 14, 'timestamp_local': '2025-03-02T18:30:00', 'timestamp_utc': '2025-03-02T13:00:00', 'ts': 1740920400}, {'aqi': 131, 'co': 1145, 'datetime': '2025-03-02:12', 'no2': 86, 'o3': 10.3, 'pm10': 62, 'pm25': 47, 'so2': 10, 'timestamp_local': '2025-03-02T17:30:00', 'timestamp_utc': '2025-03-02T12:00:00', 'ts': 1740916800}, {'aqi': 65, 'co': 383, 'datetime': '2025-03-02:11', 'no2': 129, 'o3': 5.2, 'pm10': 56, 'pm25': 19, 'so2': 16, 'timestamp_local': '2025-03-02T16:30:00', 'timestamp_utc': '2025-03-02T11:00:00', 'ts': 1740913200}, {'aqi': 87, 'co': 191.5, 'datetime': '2025-03-02:10', 'no2': 99, 'o3': 8.5, 'pm10': 55, 'pm25': 29, 'so2': 17.5, 'timestamp_local': '2025-03-02T15:30:00', 'timestamp_utc': '2025-03-02T10:00:00', 'ts': 1740909600}, {'aqi': 89, 'co': 514, 'datetime': '2025-03-02:09', 'no2': 149, 'o3': 6.2, 'pm10': 100, 'pm25': 30, 'so2': 18, 'timestamp_local': '2025-03-02T14:30:00', 'timestamp_utc': '2025-03-02T09:00:00', 'ts': 1740906000}, {'aqi': 143, 'co': 288, 'datetime': '2025-03-02:08', 'no2': 120.5, 'o3': 10.6, 'pm10': 100.5, 'pm25': 51.5, 'so2': 20.5, 'timestamp_local': '2025-03-02T13:30:00', 'timestamp_utc': '2025-03-02T08:00:00', 'ts': 1740902400}, {'aqi': 118, 'co': 413, 'datetime': '2025-03-02:07', 'no2': 166, 'o3': 4.1, 'pm10': 98, 'pm25': 42, 'so2': 21, 'timestamp_local': '2025-03-02T12:30:00', 'timestamp_utc': '2025-03-02T07:00:00', 'ts': 1740898800}, {'aqi': 76, 'co': 96.3, 'datetime': '2025-03-02:06', 'no2': 11, 'o3': 80, 'pm10': 28, 'pm25': 24, 'so2': 42, 'timestamp_local': '2025-03-02T11:30:00', 'timestamp_utc': '2025-03-02T06:00:00', 'ts': 1740895200}, {'aqi': 118, 'co': 413, 'datetime': '2025-03-02:05', 'no2': 166, 'o3': 4.1, 'pm10': 98, 'pm25': 42, 'so2': 21, 'timestamp_local': '2025-03-02T10:30:00', 'timestamp_utc': '2025-03-02T05:00:00', 'ts': 1740891600}, {'aqi': 118, 'co': 413, 'datetime': '2025-03-02:04', 'no2': 166, 'o3': 4.1, 'pm10': 98, 'pm25': 42, 'so2': 21, 'timestamp_local': '2025-03-02T09:30:00', 'timestamp_utc': '2025-03-02T04:00:00', 'ts': 1740888000}, {'aqi': 155, 'co': 192, 'datetime': '2025-03-02:03', 'no2': 122, 'o3': 6.8, 'pm10': 98.5, 'pm25': 59, 'so2': 19.5, 'timestamp_local': '2025-03-02T08:30:00', 'timestamp_utc': '2025-03-02T03:00:00', 'ts': 1740884400}, {'aqi': 146, 'co': 181.5, 'datetime': '2025-03-02:02', 'no2': 117.5, 'o3': 6.9, 'pm10': 87.5, 'pm25': 52.5, 'so2': 17, 'timestamp_local': '2025-03-02T07:30:00', 'timestamp_utc': '2025-03-02T02:00:00', 'ts': 1740880800}, {'aqi': 98, 'co': 393, 'datetime': '2025-03-02:01', 'no2': 135, 'o3': 4.2, 'pm10': 80, 'pm25': 34, 'so2': 18, 'timestamp_local': '2025-03-02T06:30:00', 'timestamp_utc': '2025-03-02T01:00:00', 'ts': 1740877200}, {'aqi': 155, 'co': 0, 'datetime': '2025-03-02:00', 'no2': 79, 'o3': 9.7, 'pm10': 78, 'pm25': 59, 'so2': 17, 'timestamp_local': '2025-03-02T05:30:00', 'timestamp_utc': '2025-03-02T00:00:00', 'ts': 1740873600}, {'aqi': 126, 'co': 413, 'datetime': '2025-03-01:23', 'no2': 138, 'o3': 4.1, 'pm10': 78, 'pm25': 45, 'so2': 20, 'timestamp_local': '2025-03-02T04:30:00', 'timestamp_utc': '2025-03-01T23:00:00', 'ts': 1740870000}, {'aqi': 146, 'co': 186.5, 'datetime': '2025-03-01:22', 'no2': 105.5, 'o3': 7, 'pm10': 80, 'pm25': 52.5, 'so2': 24, 'timestamp_local': '2025-03-02T03:30:00', 'timestamp_utc': '2025-03-01T22:00:00', 'ts': 1740866400}, {'aqi': 123, 'co': 383, 'datetime': '2025-03-01:21', 'no2': 146, 'o3': 4, 'pm10': 104, 'pm25': 44, 'so2': 26, 'timestamp_local': '2025-03-02T02:30:00', 'timestamp_utc': '2025-03-01T21:00:00', 'ts': 1740862800}, {'aqi': 159, 'co': 181.5, 'datetime': '2025-03-01:20', 'no2': 110, 'o3': 6.7, 'pm10': 108.5, 'pm25': 62, 'so2': 25, 'timestamp_local': '2025-03-02T01:30:00', 'timestamp_utc': '2025-03-01T20:00:00', 'ts': 1740859200}, {'aqi': 100, 'co': 312, 'datetime': '2025-03-01:19', 'no2': 152, 'o3': 4, 'pm10': 100, 'pm25': 35, 'so2': 16, 'timestamp_local': '2025-03-02T00:30:00', 'timestamp_utc': '2025-03-01T19:00:00', 'ts': 1740855600}, {'aqi': 179, 'co': 0, 'datetime': '2025-03-01:18', 'no2': 75, 'o3': 9.8, 'pm10': 103, 'pm25': 77, 'so2': 15, 'timestamp_local': '2025-03-01T23:30:00', 'timestamp_utc': '2025-03-01T18:00:00', 'ts': 1740852000}, {'aqi': 100, 'co': 948, 'datetime': '2025-03-01:17', 'no2': 189, 'o3': 3.9, 'pm10': 106, 'pm25': 35, 'so2': 16, 'timestamp_local': '2025-03-01T22:30:00', 'timestamp_utc': '2025-03-01T17:00:00', 'ts': 1740848400}, {'aqi': 171, 'co': 525, 'datetime': '2025-03-01:16', 'no2': 150.5, 'o3': 6.1, 'pm10': 154.5, 'pm25': 71.5, 'so2': 20, 'timestamp_local': '2025-03-01T21:30:00', 'timestamp_utc': '2025-03-01T16:00:00', 'ts': 1740844800}, {'aqi': 93, 'co': 877, 'datetime': '2025-03-01:15', 'no2': 193, 'o3': 4.8, 'pm10': 72, 'pm25': 32, 'so2': 19, 'timestamp_local': '2025-03-01T20:30:00', 'timestamp_utc': '2025-03-01T15:00:00', 'ts': 1740841200}, {'aqi': 119, 'co': 187, 'datetime': '2025-03-01:14', 'no2': 127.5, 'o3': 7.8, 'pm10': 72.5, 'pm25': 42.5, 'so2': 19, 'timestamp_local': '2025-03-01T19:30:00', 'timestamp_utc': '2025-03-01T14:00:00', 'ts': 1740837600}, {'aqi': 104, 'co': 302, 'datetime': '2025-03-01:13', 'no2': 127, 'o3': 5.8, 'pm10': 78, 'pm25': 37, 'so2': 18, 'timestamp_local': '2025-03-01T18:30:00', 'timestamp_utc': '2025-03-01T13:00:00', 'ts': 1740834000}, {'aqi': 153, 'co': 0, 'datetime': '2025-03-01:12', 'no2': 67, 'o3': 12.9, 'pm10': 73, 'pm25': 55, 'so2': 17, 'timestamp_local': '2025-03-01T17:30:00', 'timestamp_utc': '2025-03-01T12:00:00', 'ts': 1740830400}, {'aqi': 121, 'co': 302, 'datetime': '2025-03-01:11', 'no2': 133, 'o3': 6.6, 'pm10': 92, 'pm25': 43, 'so2': 17, 'timestamp_local': '2025-03-01T16:30:00', 'timestamp_utc': '2025-03-01T11:00:00', 'ts': 1740826800}, {'aqi': 161, 'co': 216.5, 'datetime': '2025-03-01:10', 'no2': 99, 'o3': 13.5, 'pm10': 120.5, 'pm25': 64, 'so2': 19.5, 'timestamp_local': '2025-03-01T15:30:00', 'timestamp_utc': '2025-03-01T10:00:00', 'ts': 1740823200}], 'lat': 17.6896, 'lon': 83.0024, 'state_code': '02', 'timezone': 'Asia/Kolkata'}

In [3]:
import pandas as pd
data = response.json()['data']
data = pd.DataFrame(data)
data

,aqi,co,datetime,no2,o3,pm10,pm25,so2,timestamp_local,timestamp_utc,ts
0,52,353.0,2025-03-04:09,132.0,5.2,58.0,13.00,23.0,2025-03-04T14:30:00,2025-03-04T09:00:00,1741078800
1,100,252.0,2025-03-04:08,105.0,8.6,73.0,35.00,22.5,2025-03-04T13:30:00,2025-03-04T08:00:00,1741075200
2,150,675.0,2025-03-04:07,139.0,6.1,128.0,54.00,13.0,2025-03-04T12:30:00,2025-03-04T07:00:00,1741071600
3,171,338.0,2025-03-04:06,113.5,9.9,125.0,71.50,11.5,2025-03-04T11:30:00,2025-03-04T06:00:00,1741068000
4,171,474.0,2025-03-04:05,133.0,7.8,156.0,71.33,13.0,2025-03-04T10:30:00,2025-03-04T05:00:00,1741064400
...,...,...,...,...,...,...,...,...,...,...,...
67,119,187.0,2025-03-01:14,127.5,7.8,72.5,42.50,19.0,2025-03-01T19:30:00,2025-03-01T14:00:00,1740837600
68,104,302.0,2025-03-01:13,127.0,5.8,78.0,37.00,18.0,2025-03-01T18:30:00,2025-03-01T13:00:00,1740834000
69,153,0.0,2025-03-01:12,67.0,12.9,73.0,55.00,17.0,2025-03-01T17:30:00,2025-03-01T12:00:00,1740830400
70,121,302.0,2025-03-01:11,133.0,6.6,92.0,43.00,17.0,2025-03-01T16:30:00,2025-03-01T11:00:00,1740826800
71,161,216.5,2025-03-01:10,99.0,13.5,120.5,64.00,19.5,2025-03-01T15:30:00,2025-03-01T10:00:00,1740823200

In [4]:
data['city_name'] = 'Anakapalle'
data

,aqi,co,datetime,no2,o3,pm10,pm25,so2,timestamp_local,timestamp_utc,ts,city_name
0,52,353.0,2025-03-04:09,132.0,5.2,58.0,13.00,23.0,2025-03-04T14:30:00,2025-03-04T09:00:00,1741078800,Anakapalle
1,100,252.0,2025-03-04:08,105.0,8.6,73.0,35.00,22.5,2025-03-04T13:30:00,2025-03-04T08:00:00,1741075200,Anakapalle
2,150,675.0,2025-03-04:07,139.0,6.1,128.0,54.00,13.0,2025-03-04T12:30:00,2025-03-04T07:00:00,1741071600,Anakapalle
3,171,338.0,2025-03-04:06,113.5,9.9,125.0,71.50,11.5,2025-03-04T11:30:00,2025-03-04T06:00:00,1741068000,Anakapalle
4,171,474.0,2025-03-04:05,133.0,7.8,156.0,71.33,13.0,2025-03-04T10:30:00,2025-03-04T05:00:00,1741064400,Anakapalle
...,...,...,...,...,...,...,...,...,...,...,...,...
67,119,187.0,2025-03-01:14,127.5,7.8,72.5,42.50,19.0,2025-03-01T19:30:00,2025-03-01T14:00:00,1740837600,Anakapalle
68,104,302.0,2025-03-01:13,127.0,5.8,78.0,37.00,18.0,2025-03-01T18:30:00,2025-03-01T13:00:00,1740834000,Anakapalle
69,153,0.0,2025-03-01:12,67.0,12.9,73.0,55.00,17.0,2025-03-01T17:30:00,2025-03-01T12:00:00,1740830400,Anakapalle
70,121,302.0,2025-03-01:11,133.0,6.6,92.0,43.00,17.0,2025-03-01T16:30:00,2025-03-01T11:00:00,1740826800,Anakapalle
71,161,216.5,2025-03-01:10,99.0,13.5,120.5,64.00,19.5,2025-03-01T15:30:00,2025-03-01T10:00:00,1740823200,Anakapalle

In [5]:
data.to_csv('datasets/Anakapalle.csv')